version: "3"

volumes:
  config:

networks:
  webgateway:
    driver: overlay
    external: true
  proxynet:
    driver: overlay

services:

  profit-trailer:
    image: helmi74/pd-profit-trailer:latest
    ports:
      - '8081:8081'
    networks:
      proxynet:
        aliases: 
          - profit-trailer
    volumes:
      - ./profit-trailer/application.properties:/profit-trailer/application.properties
      - ./profit-trailer/data:/profit-trailer/data
      - ./profit-trailer/logs:/profit-trailer/logs
    deploy:
      restart_policy:
        condition: any
      mode: global
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=pd_proxynet" # you need to change pd_ to something else if you use a different stack name when starting
        - "traefik.port=80"
        - "traefik.backend=profit-docker"
        - "traefik.backend.loadbalancer.method=drr"
        - "traefik.frontend.rule=Host:mysub.domain.com" # change this to your hostname. That hostname needs to point to your server
        - "traefik.domain=mysub.domain.com" # change this to your hostname. That hostname needs to point to your server

  pt-feeder:
    image: helmi74/pd-pt-feeder-beta:latest
    networks:
      proxynet:
        aliases:
          - pt-feeder
    volumes:
      - ./profit-trailer/application.properties:/profit-trailer/application.properties:ro
      - ./pt-feeder/config:/pt-feeder/config
      - ./pt-feeder/database:/pt-feeder/database
      - ./pt-feeder/logs:/pt-feeder/logs
    deploy:
      restart_policy:
        condition: any
      mode: global
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 5s

  pt-tracker:
    image: helmi74/pd-pt-tracker:latest
    networks:
      proxynet:
        aliases:
          - pt-tracker
    ports:
      - '3000:3000'
    volumes:
      - ./pt-tracker/PtTracker.json:/pt-tracker/PtTracker.json
      - ./pt-tracker/pttracker.db:/pt-tracker/pttracker.db
      - ./pt-tracker/pttracker.db-journal:/pt-tracker/pttracker.db-journal
      - ./pt-tracker/PtTracker.log:/pt-tracker/PtTracker.log
    deploy:
      restart_policy:
        condition: any
      mode: global
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=pd_proxynet" # you need to change pd_ to something else if you use a different stack name when starting
        - "traefik.port=3000"
        - "traefik.backend=profit-docker"
        - "traefik.backend.loadbalancer.method=drr"
        - "traefik.frontend.rule=Host:mysub-tracker.domain.com" # change this to your hostname. That hostname needs to point to your server
        - "traefik.domain=mysub-tracker.domain.com" # change this to your hostname. That hostname needs to point to your server

  pt-notifications:
    image: helmi74/pd-pt-notifications:latest
    networks:
      proxynet:
        aliases:
          - pt-tracker
    volumes:
      - ./pt-notifications/settings.properties:/pt-notifications/settings.properties
      - ./pt-notifications/database/orders.db:/pt-notifications/orders.db
      - ./pt-notifications/logs:/pt-notifications/logs
    deploy:
      restart_policy:
        condition: any
      mode: global
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 5s

  loadbalancer:
    image: traefik
    command:
      - "--loglevel=WARN"
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/etc/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onHostRule=true"
      - "--acme.httpChallenge"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.email=my@exampleemail.com"
      ## comment out the next line to request a real certificate
      - "--acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # uncomment this line if you want to test the lets encrypt certificate generation
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.exposedByDefault=false"
      - "--docker.endpoint=unix:///var/run/docker.sock"
      - "--docker.watch"
    ports:
      - 80:80
      - 443:443
      - 9090:8080
    volumes:
      - ./acme/:/etc/acme/
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: any
      mode: global
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 2s
      placement:
         constraints: [node.role == manager]
    networks:
      - proxynet
      - webgateway